// The foods that get their own page. `scan` is exactly what is sent to the
// Clear Food text scan (the same function the app uses for "log by text").
// `swap` is scanned the same way, so both scores come from the app itself.
// Add a food here, run `node scripts/scan-foods.mjs`, then `node scripts/build.mjs`.
export const FOODS = [
  { slug: 'milk', de: 'milch', name: { en: 'Milk', de: 'Milch' },
    scan: 'A glass of cow milk, 3.5% fat, 250 ml',
    swap: { name: { en: 'Unsweetened almond drink', de: 'Ungesüßter Mandeldrink' }, scan: 'A glass of unsweetened almond drink, 250 ml' } },
  { slug: 'milk-chocolate', de: 'milchschokolade', name: { en: 'Milk chocolate', de: 'Milchschokolade' },
    scan: 'Milk chocolate bar, 50 g',
    swap: { name: { en: 'Dark chocolate (85%)', de: 'Zartbitterschokolade (85 %)' }, scan: 'Dark chocolate 85% cocoa, 20 g' } },
  { slug: 'whey-protein', de: 'whey-protein', name: { en: 'Whey protein shake', de: 'Whey-Proteinshake' },
    scan: 'Whey protein shake, 30 g powder mixed with 300 ml water',
    swap: { name: { en: 'Skyr', de: 'Skyr' }, scan: 'Plain skyr, 250 g' } },
  { slug: 'energy-drink', de: 'energy-drink', name: { en: 'Energy drink', de: 'Energy Drink' },
    scan: 'Energy drink with sugar, one 500 ml can',
    swap: { name: { en: 'Sparkling water with lemon', de: 'Sprudelwasser mit Zitrone' }, scan: 'Sparkling water with a slice of lemon, 500 ml' } },
  { slug: 'cola', de: 'cola', name: { en: 'Cola', de: 'Cola' },
    scan: 'Regular cola with sugar, 500 ml bottle',
    swap: { name: { en: 'Cola zero', de: 'Cola Zero' }, scan: 'Cola zero sugar, 500 ml bottle' } },
  { slug: 'french-fries', de: 'pommes', name: { en: 'French fries', de: 'Pommes' },
    scan: 'Deep-fried french fries, medium portion 150 g',
    swap: { name: { en: 'Oven-roasted potatoes', de: 'Ofenkartoffeln' }, scan: 'Oven-roasted potatoes with a little olive oil, 200 g' } },
  { slug: 'white-toast', de: 'toastbrot', name: { en: 'White toast', de: 'Toastbrot' },
    scan: 'Two slices of white toast bread',
    swap: { name: { en: 'Wholegrain rye bread', de: 'Vollkornbrot' }, scan: 'Two slices of wholegrain rye bread' } },
  { slug: 'nutella', de: 'nutella', name: { en: 'Nutella', de: 'Nutella' },
    scan: 'Nutella hazelnut spread, 2 tablespoons (30 g)',
    swap: { name: { en: 'Peanut butter (100% peanuts)', de: 'Erdnussbutter (100 % Erdnüsse)' }, scan: 'Peanut butter made of 100% peanuts, 2 tablespoons (30 g)' } },
  { slug: 'sugary-cereal', de: 'cornflakes', name: { en: 'Frosted cornflakes', de: 'Gezuckerte Cornflakes' },
    scan: 'Frosted cornflakes with milk, bowl of 40 g cereal and 150 ml milk',
    swap: { name: { en: 'Oatmeal with berries', de: 'Haferflocken mit Beeren' }, scan: 'Oatmeal made with water, 50 g oats, topped with a handful of berries' } },
  { slug: 'gummy-bears', de: 'gummibaerchen', name: { en: 'Gummy bears', de: 'Gummibärchen' },
    scan: 'Gummy bears, 100 g bag',
    swap: { name: { en: 'Fresh berries', de: 'Frische Beeren' }, scan: 'Fresh mixed berries, 150 g' } },
  { slug: 'doner-kebab', de: 'doener', name: { en: 'Doner kebab', de: 'Döner' },
    scan: 'Doner kebab in bread with salad and sauce',
    swap: { name: { en: 'Doner plate with salad', de: 'Dönerteller mit Salat' }, scan: 'Doner meat plate with salad, no bread, light yogurt sauce' } },
  { slug: 'eggs', de: 'eier', name: { en: 'Eggs', de: 'Eier' },
    scan: 'Two boiled eggs',
    swap: null },
];
